### ISSUE TITLE
Unique id not working.

### ISSUE THREAD

**Issue by Muzorm** [alp1x/um-idcard#30]
In the old version of the script, id's were working as unique in qb-inventory and when someone else took our id and used it, my id was displayed when that person showed it. But in the new version (with photo), the original system does not work and when the other party steals and uses our identity, the identity of the person who stole it is visible. How can I fix or fix the problem?
![Screenshot_1](https://user-images.githubusercontent.com/123986261/230466200-188fc7d4-9b52-4215-b23f-a05f9ac2b24d.png)
![Screenshot_2](https://user-images.githubusercontent.com/123986261/230466291-f6f93385-846a-4da8-a537-aa1cb27eacb4.png)

**Comment by alp1x** [comment]
https://github.com/alp1x/um-idcard/releases/tag/v1.2.0
