### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by Dzurko18** [alp1x/um-idcard#36]
Getting this when using the command, getting it from the city hall as well on new character creation.
![image](https://user-images.githubusercontent.com/120120799/231888310-75289562-a787-400c-af83-957da09c6047.png)

**Comment by alp1x** [comment]
https://github.com/qbcore-framework/qb-inventory/blob/main/html/js/app.js#L394

itemData.info.firstname
  **itemData.info.firstName** etc

**Comment by Dzurko18** [comment]
Never edited the app.js
