### ISSUE TITLE
Use not ox? 

### ISSUE THREAD

**Issue by mihalyvig0202** [alp1x/um-idcard#37]
Hi. Can i use this with not ox- system? I have basic esx inventory with sql database (items) but i can add a 'driver license' item. Thx. But thanks to you, I got to know the ox system because of your identity card topic, and I can start preparing my server again, which will already work like this with the 3rd eye.  And others that I still have no idea what it contains. But first i wanna a driver license item, What I want to get after I got it in driving school.  And if I leave it, I can buy another one.  That's my plan.  I just don't have an ox system.

**Comment by alp1x** [comment]
sorry, you should use ox_inventory

**Comment by mihalyvig0202** [comment]
np, thx ur answer ;)
