### ISSUE TITLE
Erorr ! 

### ISSUE THREAD

**Issue by allyaminou** [alp1x/um-idcard#38]
When I try to use the Id card i get this in thee console, and also no card is displayed.
The first release version was working fine.  But after that i keep getting this :    
![image](https://user-images.githubusercontent.com/98634223/233779917-d05a41c2-4945-4f95-a41a-2e8a9947edad.png)

I re-installed from scratch everything. SO i don't know if it's something on my end or your script.

**Comment by alp1x** [comment]
https://alp1x.github.io/um-idcard/errors

**Comment by alp1x** [comment]
> When I try to use the Id card i get this in thee console, and also no card is displayed. The first release version was working fine. But after that i keep getting this : ![image](https://user-images.githubusercontent.com/98634223/233779917-d05a41c2-4945-4f95-a41a-2e8a9947edad.png)
> 
> I re-installed from scratch everything. SO i don't know if it's something on my end or your script.

https://alp1x.github.io/um-idcard/errors
