### ISSUE TITLE
qb-cityhall error

### ISSUE THREAD

**Issue by Save5Bucks** [alp1x/um-idcard#39]
No such export CreateMetaLicense in resource um-idcard

Im using qb-core. I have mug shot and um-idcard loaded last. everything is per your qb-core instructions.

**Comment by alp1x** [comment]
> No such export CreateMetaLicense in resource um-idcard
> 
> Im using qb-core. I have mug shot and um-idcard loaded last. everything is per your qb-core instructions.


check here, https://alp1x.github.io/um-idcard/errors
 if the problem is not solved write again and where do you use it
