### ISSUE TITLE
SCRIPT ERROR: @um-idcard/main/server.lua:17: attempt to call a nil value (global 'NewMetaDataLicense')

### ISSUE THREAD

**Issue by wSanzz** [alp1x/um-idcard#43]
Put it in last position but it still shows it

![image](https://user-images.githubusercontent.com/132177831/235331094-83b928eb-8750-4443-9ce0-3e174b6fe03a.png)
![image](https://user-images.githubusercontent.com/132177831/235331112-b51cafa8-0056-4c82-b895-57c377936e64.png)

**Comment by alp1x** [comment]
https://github.com/alp1x/um-idcard/releases/tag/v1.2.6
