### ISSUE TITLE
i have proplem withe anim this erorr how can i fix plz 

### ISSUE THREAD

**Issue by MOR6969** [alp1x/um-idcard#44]
![image](https://user-images.githubusercontent.com/89741094/235764342-a50f63c5-d1b1-465a-b190-0aeb656c341b.png)

local prop = Config.Licenses[cardType].prop

**Comment by Gametake** [comment]
i have the same error and it bug my inventory and the script dosnt work

**Comment by Gametake** [comment]
https://cdn.discordapp.com/attachments/1081064978376826911/1103052715640225822/20230502_231726.jpg

**Comment by Gametake** [comment]
dont give with /giveitem

**Comment by Kimarauskas** [comment]
> ![image](https://user-images.githubusercontent.com/89741094/235764342-a50f63c5-d1b1-465a-b190-0aeb656c341b.png)
> 
> local prop = Config.Licenses[cardType].prop

same

**Comment by alp1x** [comment]
https://github.com/alp1x/um-idcard/releases/tag/v1.2.7

**Comment by alp1x** [comment]
https://alp1x.github.io/um-idcard/errors
