### ISSUE TITLE
can you look into ps-inventory

### ISSUE THREAD

**Issue by primoixi** [alp1x/um-idcard#47]
i tried with ps-inventory but got the error SCRIPT ERROR: @um-idcard/main/server.lua:17: attempt to call a nil value (global 'NewMetaDataLicense')
I did as the document to ensure an um-id card at last but getting errors

**Comment by alp1x** [comment]
I haven't tried this with ps-inventory, I'll look into it

**Comment by alp1x** [comment]
https://github.com/alp1x/um-idcard/blob/main/bridge/inventory/ps.lua
